Checker 1.5
- Produced piece objects to place in a multidimensional array

*Need to make the multidimensional array, running into
 Error: Object reference not set to an instance of an object.